server:
  port: 9999

spring:
  application:
    name: service8888 #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://192.168.1.111:3306/redis_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    host: 192.168.1.101
    port: 6379
    password:
    database: 0 # Redis数据库索引(默认为0)
    timeout: 60000 # 连接超时时间（毫秒)
    lettuce:
      pool:
        max-idle: 16 # 最大空闲连接数
        max-active: 32 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 8 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）





#devtools:
#  restart:
#    enabled: true #是否支持热部署


#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true #开启驼峰命名法
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    com.rj.springboot: debug
